name: mobilenet_v2_imagenet_ssld
dir: "modules/image/classification/mobilenet_v2_imagenet_ssld"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/cv/mobilenet_v2_imagenet_ssld_pretrained.tar.gz
    dest: model
    uncompress: True
