name: mobilenet_v2_dishes
dir: "modules/image/classification/mobilenet_v2_dishes"
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/cv/mobilenet_v2_dishes.tar.gz
    dest: model
    uncompress: True
