name: resnet50_vd_10w
dir: "modules/image/classification/resnet50_vd_10w"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/cv/resnet50_vd_10w_pretrained.tar.gz
    dest: model
    uncompress: True
